### ISSUE TITLE
Task dependencies don't work when calling any of the plugin tasks

### ISSUE THREAD

**Issue by AmundsenJunior** [umayrh/gradle-plugin-r#1]
When running Gradle tasks such as `packratRestore` or `document`, it is expected by the plugin configuration that `installDeps` or `packratRestore` would be called, respectively, as dependent tasks. This does not happen. `installDeps` must be explicitly called in order to properly set up the environment, which is necessary when using this plugin for an R package as part of my CI.

**Comment by umayrh** [comment]
@AmundsenJunior Did you try that from inside an R projects? Here's the task tree from the `rUtils` package:

```
$ gradle build :R:rUtils:taskTree

> Task :R:rUtils:taskTree

------------------------------------------------------------
Project :R:rUtils - R Utilities
------------------------------------------------------------

:R:rUtils:build
+--- :R:rUtils:assemble
\--- :R:rUtils:check
     \--- :R:rUtils:test
          \--- :R:rUtils:document
               \--- :R:rUtils:packratRestore
                    \--- :R:rUtils:installDeps
```

And it seems correct. Maybe your project isn't fully set up, or perhaps I misunderstood the problem. Let me know.

**Comment by AmundsenJunior** [comment]
@umayrh can you link to the rUtils package, so that I can reference its setup? I want to make sure I'm fully set up in my R project appropriately before debugging further.

**Comment by umayrh** [comment]
@AmundsenJunior here's the link to [rUtils](https://github.com/umayrh/sketchy-polytopes/tree/master/R/rUtils), which uses its parent project's [build.gradle](https://github.com/umayrh/sketchy-polytopes/blob/master/R/build.gradle).

**Comment by AmundsenJunior** [comment]
Thanks @umayrh - I'm not sure what was wrong in my project config. This is working correctly.
