### ISSUE TITLE
Use CRAN instead of GitHub for released versions of roxygen2 and usethis instead of dev versions

### ISSUE THREAD

**Issue by AmundsenJunior** [umayrh/gradle-plugin-r#2]
Was encountering errors from installDeps task when attempting to install roxygen in my CI process:

```
Downloading GitHub repo klutometis/roxygen@master
Error in read.dcf(file = tmpf) : cannot open the connection
Calls: <Anonymous> ... package_deps -> available_packages -> available_packages_set
Execution halted
:installDeps FAILED
```

Was resolved by skipping the installDeps task, and installing the released roxygen2 package from CRAN. I think in general it'd be more stable to only install released versions of these dependencies.

I'm sorry that I don't have better evidence to support the request, but all my recent attempts to install roxygen2 either in a CI process or locally (on my Mac OS X) have failed when using the devtools::install_github() from source method.

**Comment by umayrh** [comment]
Thanks for the feedback. I haven't yet encountered issues installing R packages from Github but it's probably better to use CRAN versions. I've updated the `installDeps` task to download packages from CRAN only. You can try it out by pulling version 0.2.5 (https://plugins.gradle.org/plugin/com.umayrh.rplugin):

```
plugins {
  id "com.umayrh.rplugin" version "0.2.5"
}
```

Let me know if you encounter any issues.

**Comment by AmundsenJunior** [comment]
Yes, it does work successfully for me again! Thank you.


Sidenote @umayrh, the plugin is no longer available as "gradle-plugin-r", but as just "plugin"? Is that right? 

`classpath 'gradle.plugin.com.umayrh:gradle-plugin-r:0.2.4'`
versus 
`classpath 'gradle.plugin.com.umayrh:plugin:0.2.5'`

The former dependency structure did not resolve for me for 0.2.5, only the latter did.
